#-----------camera----------
-
    name: "BEV_CAM_RGB"
    modality: 'camera_bev'

-
    name: "MULTI_CAM_RGB_0"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_1"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_2"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_3"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_4"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_5"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_6"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_7"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_8"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_9"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_10"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_11"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_12"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_13"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_14"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_15"
    modality: 'camera'

-
    name: "MULTI_CAM_RGB_16"
    modality: 'camera'

#-----------radar----------
- 
    name: "RADAR_FRONT"
    modality: 'radar'

- 
    name: "RADAR_FRONT_RIGHT"
    modality: 'radar'


- 
    name: "RADAR_FRONT_LEFT"
    modality: 'radar'

- 
    name: "RADAR_BACK_RIGHT"
    modality: 'radar'

- 
    name: "RADAR_BACK_LEFT"
    modality: 'radar'

#-----------lidar----------
- 
    name: 'LIDAR_TOP'
    modality: 'lidar'
